# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
pre_cmd = []
cmd = "go build -o ./tmp/main ."
include_ext = ["go"]